// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wcoozqxyzvayxzwnogez.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indjb296cXh5enZheXh6d25vZ2V6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDExMDI5NzEsImV4cCI6MjA1NjY3ODk3MX0.LQry69OlqECgqpapf-QP4rHfzFVcQnAG-bc8Iy_qBCg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);